hw5-django-demo/lms/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    path('groups/', views.GroupList.as_view()),
    path('groups/<int:pk>/', views.GroupList.as_view()),
    path('students/',
         views.StudentViewSet.as_view(
             {'get': 'list',
              'post': 'create'}
         )),
    path('students/<int:pk>/',
         views.StudentViewSet.as_view(
             {'get': 'retrieve',
              'put': 'update',
              'delete': 'destroy'}
         )),
    path('teachers/', views.TeacherViewSet.as_view(
        {'get': 'list',
         'post': 'create'}
    )),
    path('teachers/<int:pk>/', views.TeacherViewSet.as_view(
        {'get': 'retrieve',
         'put': 'update',
         'delete': 'destroy'}
    )),
]

urlpatterns = format_suffix_patterns(urlpatterns)

hw5-django-demo/lms/lms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core.views import GroupView, TeacherView, StudentView, IndexView
from core.views import CreateGroupView, CreateTeacherView, CreateStudentView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/',include(debug_toolbar.urls)),
    path('', IndexView.as_view(template_name='group_detail.html'), name="home"),
    path('group/', GroupView.as_view()),
    path('teacher/', TeacherView.as_view()),
    path('student/', StudentView.as_view()),
    path('group/create/', CreateGroupView.as_view()),
    path('teacher/create/', CreateTeacherView.as_view()),
    path('student/create/', CreateStudentView.as_view()),
]

hw5-django-demo/lms/core/models.py
from django.db import models
from django.core.validators import RegexValidator


class Group(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    teacher = models.ManyToManyField('core.Teacher')

    def __str__(self):
        return self.name


class Student(models.Model):
    fullname = models.CharField(max_length=255)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    birthday = models.DateField(auto_now=False, auto_now_add=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+380123456789'")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    age = models.PositiveSmallIntegerField(default=14)

    def __str__(self):
        return self.fullname


class Teacher(models.Model):
    fullname = models.CharField(max_length=255)
    birthday = models.DateField(auto_now=False, auto_now_add=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+380123456789'")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        return self.fullname

hw5-django-demo/lms/core/forms.py
from django import forms
from core.models import Student, Group, Teacher


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'

hw5-django-demo/lms/core/views.py
from django.views.generic import FormView
from django.views.generic.list import ListView
from core.models import Group, Teacher, Student
from django.db.models import F
from django.db.models.aggregates import Avg, Count, Max, Min
from core.forms import StudentForm, GroupForm, TeacherForm
from django.shortcuts import get_object_or_404


class IndexView(ListView):
    """
    Show main info about all groups
    """
    template_name = "group_detail.html"

    def get_queryset(self):
        return Group.objects.get_queryset(
        ).annotate(
            teacher_name=F('teacher__fullname'),
            student_count=Count('student'),
            student_avg_age=Avg('student__age'),
            student_max_age=Max('student__age'),
            student_min_age=Min('student__age'),
        )


class GroupView(ListView):
    """
    Show all info about the group
    """
    template_name = "group.html"
    model = Group


class CreateGroupView(FormView):
    """
    Create a new group using the model Group
    """
    template_name = 'create.html'
    form_class = GroupForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(CreateGroupView, self).get_context_data(**kwargs)
        context['action'] = 'Create'
        return context

    def form_valid(self, form):
        form.save()
        return super(CreateGroupView, self).form_valid(form)


class UpdateGroupView(FormView):
    """
    Update the selected group
    """
    template_name = 'create.html'
    form_class = GroupForm
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        group = get_object_or_404(Group, pk=self.kwargs.get('pk'))
        kwargs.update({'instance': group})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(UpdateGroupView, self).get_context_data(**kwargs)
        context['button_name'] = 'Update'
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        form.save()
        return super(UpdateGroupView, self).form_valid(form)


class TeacherView(ListView):
    """
    Show all info about teacher using model
    """
    template_name = "teacher.html"
    model = Teacher


class CreateTeacherView(FormView):
    """
    Create a new teacher using the model Teacher
    """
    template_name = 'create.html'
    form_class = TeacherForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(CreateTeacherView, self).get_context_data(**kwargs)
        context['action'] = 'Create'
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        form.save()
        return super(CreateTeacherView, self).form_valid(form)


class UpdateTeacherView(FormView):
    """
    Update the selected teacher
    """
    template_name = 'create.html'
    form_class = TeacherForm
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        teacher = get_object_or_404(Teacher, pk=self.kwargs.get('pk'))
        kwargs.update({'instance': teacher})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(UpdateTeacherView, self).get_context_data(**kwargs)
        context['action'] = 'Update'
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        form.save()
        return super(UpdateTeacherView, self).form_valid(form)


class StudentView(ListView):
    template_name = "student.html"
    model = Student


class CreateStudentView(FormView):
    """
    Create a new student using the model Student
    """
    template_name = 'create.html'
    form_class = StudentForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(CreateStudentView, self).get_context_data(**kwargs)
        context['action'] = 'Create'
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        form.save()
        return super(CreateStudentView, self).form_valid(form)


class UpdateStudentView(FormView):
    """
    Update the selected student
    """
    template_name = 'create.html'
    form_class = StudentForm
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        student = get_object_or_404(Student, pk=self.kwargs.get('pk'))
        kwargs.update({'instance': student})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(UpdateStudentView, self).get_context_data(**kwargs)
        context['action'] = 'Update'
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        form.save()
        return super(UpdateStudentView, self).form_valid(form)

hw5-django-demo/lms/core/templates/contact_done.html
{% extends 'index.html' %}
{% load bootstrap_tags %}
{% block body %}

<style>
  body {
    text-align: center;
    background: #EBF0F5;
  }
    h1 {
      color: #88B04B;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-weight: 900;
      font-size: 40px;
      margin-bottom: 10px;
    }
    p {
      color: #404F5E;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size:20px;
      margin: 0;
    }
  i {
    color: #9ABC66;
    font-size: 100px;
    line-height: 200px;
    margin-left:-15px;
  }
  .card {
    background: white;
    padding: 60px;
    border-radius: 4px;
    box-shadow: 0 2px 3px #C8D0D8;
    display: inline-block;
    margin: 0 auto;
  }
</style>
<body>
  <div class="card">
  <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
    <i class="checkmark">✓</i>
  </div>
    <h1>Success</h1>
    <p>We have received your message! <br/> We'll reached you out immediately!</p>
  </div>

{% endblock %}

hw5-django-demo/lms/core/templates/contact_us.html
{% extends 'index.html' %}
{% load bootstrap_tags %}
{% block body %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<div class="container">
	<div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
          <form class="form-horizontal" action="" method="post">{% csrf_token %}
          <fieldset>
            <legend class="text-center">Contact us</legend>

            <!-- Name input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name">Name</label>
              <div class="col-md-9">
                <input id="name" name="name" type="text" placeholder="Your name" class="form-control">
              </div>
            </div>

            <!-- Email input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="email">Your E-mail</label>
              <div class="col-md-9">
                <input id="email" name="email" type="text" placeholder="Your email" class="form-control">
              </div>
            </div>

            <!-- Message body -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="message">Your message</label>
              <div class="col-md-9">
                <textarea class="form-control" id="message" name="message" placeholder="Please enter your message here..." rows="5"></textarea>
              </div>
            </div>

            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
              </div>
            </div>
          </fieldset>
          </form>
        </div>
      </div>
	</div>
</div>
{% endblock %}

hw5-django-demo/lms/core/templates/create.html
{% extends 'index.html' %} {% load bootstrap_tags %} {% block body %}
<body>
  <div class="container">
    <form method="post" enctype="multipart/form-data" novalidate>
      {% csrf_token %} {{ form|as_bootstrap_horizontal }}
      <button type="submit">{{ action }}</button>
    </form>
  </div>
</body>
{% endblock %}

hw5-django-demo/lms/core/templates/dtl.html
{% extends 'index.html' %} {% load core_tags %} {% block body %}

<div class="row" style="margin-left: 2.5em">
  <h1>DTL tasks</h1>
</div>

<div class="container-space">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Group name</th>
        <th scope="col">Teacher</th>
      </tr>
    </thead>
    {% random_teachers %}
  </table>
</div>
{% endblock %}

hw5-django-demo/lms/core/templates/group.html
{% extends 'index.html' %} {% block body %}

<div class="row" style="margin-left: 2.5em">
  <h1>Groups list</h1>
</div>
<div class="container-space">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Group</th>
        <th scope="col">Teacher</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for group in object_list.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <th><a href="/group/{{group.id}}">{{group}}</a></th>
        {% for teacher in group.teacher.all %}
        <th><a href="/teacher/{{teacher.id}}">{{ teacher }}</a></th>
        <th>
          <form method="get" action="/group/{{group.id}}">
            <input
              type="submit"
              value="UPDATE"
              class="btn btn-secondary btn-sm"
            />
          </form>
        </th>
      </tr>
      {% endfor %} {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

hw5-django-demo/lms/core/templates/group_detail.html
{% extends 'index.html' %} {% block body %}

<div class="row" style="margin-left: 2.5em">
  <h1>Groups list</h1>
</div>
<div class="container-space">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Group name</th>
        <th scope="col">Teacher</th>
        <th scope="col">Number of students</th>
        <th scope="col">Average age of students</th>
        <th scope="col">Maximum age of student</th>
        <th scope="col">Minimal age of student</th>
      </tr>
    </thead>
    <tbody>
      {% for group in object_list.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <th><a href="/group/{{group.id}}">{{group}}</a></th>
        <th>
          <a href="/teacher/{{group.teacher_id}}">{{ group.teacher_name }}</a>
        </th>
        <th scope="row">{{ group.student_count}}</th>
        <th scope="row">{{ group.student_avg_age}}</th>
        <th scope="row">{{ group.student_max_age}}</th>
        <th scope="row">{{ group.student_min_age}}</th>
        {% endfor %}
      </tr>
    </tbody>
  </table>
</div>

{% endblock %}

hw5-django-demo/lms/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>LMS</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
  </head>
  <nav class="navbar navbar-expand-sm bg-light navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/">LMS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/group">Group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/teacher">Teacher</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/student">Student</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/group/create">Create group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/student/create">Create student</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/teacher/create">Create teacher</a>
      </li>
    </ul>
  </nav>
  <body>
    {% block body %} {% endblock %}
  </body>
</html>

hw5-django-demo/lms/core/templates/student.html
{% extends 'index.html' %} {% block body %}
<div class="row" style="margin-left: 2.5em"><h1>Students list</h1></div>
<div class="container-space">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Student</th>
        <th scope="col">Group</th>
        <th scope="col">Phone number</th>
        <th scope="col">Email</th>
        <th scope="col">Birthday</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for student in object_list.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <th scope="row">{{ student.fullname }}</th>
        <th><a href="/group/{{student.group.id}}">{{ student.group }}</a></th>
        <th scope="row">{{ student.phone_number }}</th>
        <th scope="row">{{ student.email }}</th>
        <th scope="row">{{ student.birthday }}</th>
        <th>
          <form method="get" action="/student/{{student.id}}">
            <input
              type="submit"
              value="UPDATE"
              class="btn btn-secondary btn-sm"
            />
          </form>
        </th>
        {% endfor %}
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

hw5-django-demo/lms/core/templates/teacher.html
{% extends 'index.html' %} {% block body %}
<div class="row" style="margin-left: 2.5em"><h1>Teachers list</h1></div>
<div class="container-space">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Teacher</th>
        <th scope="col">Group</th>
        <th scope="col">Phone number</th>
        <th scope="col">Email</th>
        <th scope="col">Birthday</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for teacher in object_list.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <th scope="row">{{ teacher.fullname }}</th>
        {% for group in teacher.group_set.all %}
        <th><a href="/group/{{group.id}}">{{ group }}</a></th>
        {% endfor %}
        <th scope="row">{{ teacher.phone_number }}</th>
        <th scope="row">{{ teacher.email }}</th>
        <th scope="row">{{ teacher.birthday }}</th>
        <th>
          <form method="get" action="/teacher/{{teacher.id}}">
            <input
              type="submit"
              value="UPDATE"
              class="btn btn-secondary btn-sm"
            />
          </form>
        </th>
        {% endfor %}
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}